name: Cypress Tests CI/CD

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Cypress GitHub Action
        uses: cypress-io/github-action@v2
      

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:run --record --key $CYPRESS_RECORD_KEY
